<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="Vinay-PV" failures="1" tests="1" name="Test1" time="11.582" errors="0" timestamp="2022-05-11T07:05:22 IST">
  <testcase classname="script.Demo1" name="test1" time="1.257">
    <failure type="java.lang.AssertionError" message="expected [xyz] but found [abcd]">
      <![CDATA[java.lang.AssertionError: expected [xyz] but found [abcd]
at script.Demo1.test1(Demo1.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="script.Demo3" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase classname="generic.BaseTest" name="@BeforeSuite initReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite initReport -->
  <testcase classname="script.Demo2" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase classname="generic.BaseTest" name="@AfterSuite publishReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite publishReport -->
  <testcase classname="generic.BaseTest" name="@BeforeSuite initReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite initReport -->
  <testcase classname="generic.BaseTest" name="@AfterSuite publishReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite publishReport -->
</testsuite> <!-- Test1 -->
